# Generated by Django 4.2.3 on 2023-07-13 08:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completed_courses_num', models.IntegerField(default=0)),
                ('completed_lessons_num', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuizSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passed', models.BooleanField(default=False)),
                ('total_points', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('quiz_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.quiz')),
                ('user_progress_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.userprogress')),
            ],
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('progress', models.IntegerField(default=0)),
                ('completion_date', models.DateField(default=datetime.date.today)),
                ('completed', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.userprogress')),
            ],
        ),
        migrations.CreateModel(
            name='UserLessonChapterProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('progress', models.IntegerField(default=0)),
                ('completion_date', models.DateField(default=datetime.date.today)),
                ('completed', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessonchapter')),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.userprogress')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('progress', models.IntegerField(default=0)),
                ('completion_date', models.DateField(default=datetime.date.today)),
                ('completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.userprogress')),
            ],
        ),
        migrations.CreateModel(
            name='UserAssignmentSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='static/assignments/')),
                ('passed', models.BooleanField(default=False)),
                ('total_points', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('assignment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.assignment')),
                ('user_progress_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.userprogress')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLedgerRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lessonchapter')),
                ('user_progress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.userprogress')),
            ],
        ),
    ]
