# Generated by Django 4.2.3 on 2023-07-13 08:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('bio', models.CharField(blank=True, max_length=2000, null=True)),
                ('profile_pic_file', models.FileField(blank=True, null=True, upload_to='static/authors/')),
                ('facebook_url', models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.URLValidator()])),
                ('instagram_url', models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('level', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanded', 'Advanced')], default='Basic', max_length=200)),
                ('course_small_image', models.FileField(blank=True, null=True, upload_to='static/courses/')),
                ('course_large_image', models.FileField(blank=True, null=True, upload_to='static/courses/')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.author')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='LessonChapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Video', 'Video'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment')], default='Video', max_length=200)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessonchapter')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('points', models.IntegerField(default=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.URLValidator()])),
                ('video_file', models.FileField(blank=True, null=True, upload_to='static/media/')),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('points', models.IntegerField(default=100, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessonchapter')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=1000)),
                ('points', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessonchapter')),
            ],
        ),
    ]
